[package]
name = "cpuid"
version = "0.1.0"
authors = ["Amazon firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
kvm-bindings = "0.1"

kvm-ioctls =  { path = "../kvm-ioctls" }
hypervisor =  { path = "../hypervisor" }
